Improve logging
keboola/google-client-bundle pull request #10
Opened 2022-06-20 13:59 UTC by AdamVyborny

JIRA: https://keboola.atlassian.net/browse/COM-1550

2022-06-21 13:08 UTC, AdamVyborny commented
@ondrajodas přidal jsem ten reason do message. Nevím, proč ten context je v paper trail prázdný 🤷‍♂️

2022-06-22 07:49 UTC, AdamVyborny commented
@ondrajodas zmigrováno

2022-06-22 12:46 UTC, ondrajodas requested changes

2022-06-22 12:46 UTC, ondrajodas commented on src/Google/RestApi.php
> +            if (array_key_exists('Authorization', $headersForLog)) {
to že se to převádělo na malé písmena mělo bych řekl nějaký důvod a nechal bych to tu

2022-06-22 12:55 UTC, AdamVyborny commented on src/Google/RestApi.php
> +            if (array_key_exists('Authorization', $headersForLog)) {
zachováno

2022-06-23 07:46 UTC, ondrajodas approved these changes

2022-06-23 08:41 UTC, merged